### ISSUE TITLE
colon in gazebo:world_name:model_name

### ISSUE THREAD

**Issue by joaobrittoneto** [rock-gazebo/simulation-rock_gazebo#11]
When checking the log file of rock-gazebo with a ruby script, the colon in task's name causes some trouble.

The example below causes a `SyntaxError: unexpected ':', expecting end-of-input`
```
log = Orocos::Log::Replay.open(file)
gazebo_task = log.gazebo:world_name:model_name
```
The task can be accessed as below, but IMO it's not straightforward.
```
gazebo_task = log.send('gazebo:world_name:model_name')
```

Is it possible to remove the colon from the [task's name](https://github.com/rock-gazebo/simulation-rock_gazebo/blob/master/bindings/ruby/lib/rock_gazebo/orogen_model_from_sdf_world.rb#L19)? Maybe something like `gazebo-world_name-model_name`?

**Comment by doudou** [comment]
I would rather not change something like this now - it would break a lot of existing code. For something better than `send`, use `#task` (`replay.task('name:of:task')`)

**Comment by doudou** [comment]
For what it's worth `-` would not have worked either. The method call has to be a valid identifier, which means that the only valid non-alphanumeric separator is the underscore (thus losing the "separator")

**Comment by joaobrittoneto** [comment]
No problem.
A lit bit out of topic, but may be the case to have documented where logs are saved in syskit, how to process logfiles, access  data (including the `replay.task('name:of:task')`) , and so on,  on the new [website](https://rock-core.github.io/rock-and-syskit/). Something like the old one [has](https://www.rock-robotics.org/master/documentation/data_analysis/replaying_logfiles.html).

**Comment by doudou** [comment]
> A lit bit out of topic, but may be the case to have documented where logs are saved in syskit, how to process logfiles, access data (including the replay.task('name:of:task')) , and so on, on the new website. Something like the old one has.

Absolutely ! This website is very much open to contributions .... (wink, wink)
