### ISSUE TITLE
Joint position

### ISSUE THREAD

**Issue by alexfneves** [rock-gazebo/simulation-rock_gazebo#2]
Hello,

I was doing a simulation of my system in rock-gazebo, and something weird was happening. This wasn't happening before, but I haven't done this simulation in more than a month. The .world file includes a model. The error occurs on the joint position of the model included.

In this example I set the position of the model on the world as `<pose>1 0 0 0 0 0</pose>`.

This is what happens when I use the `gazebo` command.
![image](https://user-images.githubusercontent.com/3381707/32913217-d325e010-caf8-11e7-932a-5cf41cfce4e7.png)

This is what happens when I start the world with the `rock-gazebo` command.
![image](https://user-images.githubusercontent.com/3381707/32913509-b27381e6-caf9-11e7-926c-790d636f669e.png)

While the model and its joints seems to be in `x = 1`, with `gazebo`, in `rock-gazebo` the links are in  `x = 1` but the joint are in `x = 2`. It seems like the joints position of the model included in the `<world>` are adding the model position twice instead of once.

Any ideas why?

**Comment by doudou** [comment]
Could you pass a (hopefully minimal) SDF file that shows the problem ? It would help ...

**Comment by alexfneves** [comment]
This is the .world file I'm using. What matters is the `<pose>` inside the` <include>`  tag. The included model has 3 revolute joints that can be shown in the gazebo.

```
<?xml version='1.0'?>
<sdf version='1.6'>
  <world name='HEADS_world'>
    <light name='sun' type='directional'>
      <cast_shadows>1</cast_shadows>
      <pose frame=''>0 0 10 0 -0 0</pose>
      <diffuse>0.8 0.8 0.8 1</diffuse>
      <specular>0.1 0.1 0.1 1</specular>
      <attenuation>
        <range>1000</range>
        <constant>0.9</constant>
        <linear>0.01</linear>
        <quadratic>0.001</quadratic>
      </attenuation>
      <direction>-0.5 0.5 -1</direction>
    </light> 
    <gravity>0 0 -9.81</gravity>
    <magnetic_field>6e-06 2.3e-05 -4.2e-05</magnetic_field>
    <atmosphere type='adiabatic'/>
    <physics name='default_physics' default='0' type='ode'>
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1</real_time_factor>
      <real_time_update_rate>1000</real_time_update_rate>
    </physics>
    <scene>
      <ambient>0.8 0.8 0.8 1</ambient>
      <background>0.8 0.8 0.8 1</background>
      <shadows>0</shadows>
    </scene>
    <spherical_coordinates>
      <surface_model>EARTH_WGS84</surface_model>
      <latitude_deg>0</latitude_deg>
      <longitude_deg>0</longitude_deg>
      <elevation>0</elevation>
      <heading_deg>0</heading_deg>
    </spherical_coordinates>

    <model name="ship_and_heads">
        <include>
          <name>heads</name>
          <uri>model://heads</uri>
          <pose>1 0 0 0 0 0</pose>
        </include>
        <joint name="attached_to_ground" type="fixed">
            <parent>world</parent>
            <child>heads::base</child>
        </joint>
    </model>
  </world>
</sdf>
```

**Comment by doudou** [comment]
Should be fixed by https://github.com/rock-control/control-ruby_sdformat/pull/22, could you give it a try ?

**Comment by alexfneves** [comment]
It seems to be working again, thank you!
